version: '3.8'

services:
  frontend:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=http://localhost:8000
      - NEXT_PUBLIC_WS_URL=ws://localhost:8000
    depends_on:
      - backend
    networks:
      - voicecare-network

  backend:
    image: voicecare-backend:latest
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=sqlite+aiosqlite:///./voicecare.db
      - CORS_ORIGINS=["http://localhost:3000"]
    volumes:
      - ./data:/app/data
    networks:
      - voicecare-network

networks:
  voicecare-network:
    driver: bridge
